spring.application.name=EvGenee
server.port=2030


spring.datasource.url=jdbc:mysql://localhost:3306/evgenee
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

jwt.secret=

websocket.ping.timeout=60000
websocket.ping.interval=25000

socketio.host=0.0.0.0
socketio.port=2031

spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.temperature=0.1

platform.fee.percentage=20.0
